name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    name: Check Code Style with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install black
      - name: Run Black
        run: black --check .

  test:
    name: Run Tests and Generate Coverage Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install pytest coverage
          pip install numpy matplotlib
      - name: Run Tests with Coverage
        run: coverage run -m pytest
      - name: Verify .coverage File Exists
        run: ls -la .coverage  # Debug: Ensure .coverage is generated
      - name: Upload Coverage Data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage
          retention-days: 7  # Increased retention for testing purposes

  coverage_report:
    name: Generate and Upload Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Download Coverage Data
        uses: actions/download-artifact@v4
        with:
          name: coverage-data
      - name: Verify Downloaded .coverage File
        run: ls -la  # Debug: Ensure artifact was downloaded
      - name: Generate Coverage Report
        run: |
          pip install coverage
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 14
