name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    name: Check Code Style with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install black
      - name: Run Black
        run: black --check .

  test:
    name: Run Tests, Collect Coverage, Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install pytest coverage
          pip install numpy matplotlib

      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest
          coverage report -m
          coverage html

      - name: Verify .coverage File
        run: ls -la .coverage  # Confirm the file exists
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: .coverage  # Corrected path for coverage file
          retention-days: 1
      - name: Generate Coverage Report
        run: |
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 14

  update_readme_badge:
    name: Add CI/CD Badge to README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update README.md with CI Badge
        run: |
          echo "![SSE CI/CD](https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg)" > temp_readme
          if [ -f README.md ]; then
            grep -v '!\[SSE CI/CD\]' README.md >> temp_readme
          fi
          mv temp_readme README.md
          cat README.md
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md with CI Badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
