name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    name: Check Code Style with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install black
      - name: Run Black
        run: black --check .

  test:
    name: Run Tests and Collect Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install pytest coverage
          pip install numpy matplotlib

      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest
          coverage report -m
          coverage html
      - name: Verify .coverage File
        run: ls -la .coverage  # Confirm the file exists
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: .coverage  # Corrected path for coverage file
          retention-days: 1

  coverage_report:
    name: Generate Coverage Report
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Coverage
        run: pip install coverage
      - name: Generate Coverage Report
        run: |
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 14

  update_readme_badge:
    name: Update GitHub Workflow Badge in README.md
    runs-on: ubuntu-latest
    needs: coverage_report
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive.key | sudo gpg --dearmor -o /usr/share/keyrings/github-archive-keyring.gpg
          sudo apt-get update
          sudo apt-get install gh
      - name: Update README.md with Badge
        run: |
          gh repo edit --add-readme-file --body "
          ![SSE CI/CD](https://github.com/<your-username>/<your-repo>/actions/workflows/ci.yml/badge.svg)"
          git commit -am "Update README with CI/CD Badge"
          git push