name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    name: Check Code Style with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install black
      - name: Run Black
        run: black --check .

  test:
    name: Run Tests, Collect Coverage, Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install pytest coverage
          pip install numpy matplotlib

      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest
          coverage report -m
          coverage html

      - name: Verify .coverage File
        run: ls -la .coverage  # Confirm the file exists
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: .coverage  # Corrected path for coverage file
          retention-days: 1
      - name: Generate Coverage Report
        run: |
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 14

  update_readme_badge:
    name: Update GitHub Workflow Badge in README.md
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y
      - name: Update README.md with Badge
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh repo edit --add-readme-file --body "
          ![SSE CI/CD](https://github.com/ombahiwal/automation-exercise-wt2425/actions/workflows/ci.yml/badge.svg)"
          git commit -am "Update README with CI/CD Badge"
          git push
